import { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties } = {
  nav: {
    background: "#254260",
    padding: "6px 30px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    boxShadow: "0 2px 8px rgba(0,0,0,0.2)",
    fontFamily: "'Poppins', sans-serif",
  },
  menu: {
    display: "flex",
    gap: "40px",
    flexWrap: "wrap",
    alignItems: "center",
  },
  link: {
    color: "#fff",
    textDecoration: "none",
    fontFamily: "'Poppins', sans-serif",
    fontWeight: "300",
    fontSize: "20px",
    lineHeight: "100%",
    letterSpacing: "2%",
    transition: "all 0.3s ease",
    padding: "8px 0",
    borderRadius: "4px",
    position: "relative",
  },
  activeLink: {
    color: "#fff",
    textDecoration: "none",
    fontFamily: "'Poppins', sans-serif",
    fontWeight: "700",
    fontSize: "20px",
    lineHeight: "100%",
    letterSpacing: "2%",
    transition: "all 0.3s ease",
    padding: "8px 0",
    position: "relative",
    borderBottom: "3px solid #64b5f6",
  },
  linkExtraBold: {
    color: "#fff",
    textDecoration: "none",
    fontSize: "18px",
    fontWeight: "700",
    fontFamily: "'Poppins', sans-serif",
    letterSpacing: "0.3px",
    transition: "all 0.3s ease",
    padding: "8px 0",
  },
  linkSuperBold: {
    color: "#fff",
    textDecoration: "none",
    fontSize: "18px",
    fontWeight: "800",
    fontFamily: "'Poppins', sans-serif",
    letterSpacing: "0.3px",
    transition: "all 0.3s ease",
    padding: "8px 0",
  },
  linkHover: {
    transform: "translateY(-2px)",
  },
  rightSide: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: "20px",
  },
  loginBtn: {
    background: "#1e88e5",
    color: "#fff",
    padding: "10px 24px",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "600",
    fontFamily: "'Poppins', sans-serif",
    boxShadow: "0 2px 8px rgba(30, 136, 229, 0.3)",
    transition: "all 0.3s",
  },
  rightLink: {
    color: "#fff",
    textDecoration: "none",
    fontSize: "16px",
    fontWeight: "600",
    fontFamily: "'Poppins', sans-serif",
    padding: "8px 16px",
    borderRadius: "6px",
    background: "#1e88e5",
    boxShadow: "0 2px 6px rgba(30,136,229,0.3)",
    transition: "all 0.3s",
  },
  profileWrapper: {
    position: "relative",
  },
  profileIcon: {
    width: "40px",
    height: "40px",
    background: "#fff",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: "20px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.2)",
    transition: "all 0.3s",
  },
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "transparent",
    zIndex: 998,
  },
  dropdown: {
    position: "absolute",
    top: "50px",
    right: "0",
    background: "#fff",
    borderRadius: "12px",
    boxShadow: "0 8px 24px rgba(0,0,0,0.15)",
    width: "320px",
    zIndex: 999,
    maxHeight: "calc(100vh - 80px)",
    overflowY: "auto",
    fontFamily: "'Poppins', sans-serif",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: "rgba(0, 0, 0, 0.6)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 999,
    backdropFilter: "blur(4px)",
  },
  modal: {
    background: "#fff",
    padding: "30px",
    borderRadius: "12px",
    width: "90%",
    maxWidth: "400px",
    boxShadow: "0 10px 40px rgba(0,0,0,0.3)",
    fontFamily: "'Poppins', sans-serif",
  },
  dropdownItem: {
    padding: "12px 20px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
    color: "#333",
    textDecoration: "none",
    fontSize: "14px",
    fontWeight: "500",
    transition: "background 0.2s",
    borderBottom: "1px solid #f0f0f0",
  },
  dropdownItemLast: {
    padding: "12px 20px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
    color: "#333",
    textDecoration: "none",
    fontSize: "14px",
    fontWeight: "500",
    transition: "background 0.2s",
    borderBottom: "none",
  },
  aboutDropdown: {
    position: "absolute",
    top: "100%",
    left: "0",
    background: "#fff",
    borderRadius: "8px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
    minWidth: "220px",
    zIndex: 1000,
    marginTop: "8px",
    overflow: "hidden",
  }
};
